# Generated by Django 2.1.4 on 2018-12-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='relative_dir',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo',
            name='deep_link',
            field=models.URLField(max_length=2048),
        ),
    ]
